package service;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.util.Random;

/**
 * This will implement functionality needed to have events for the persons generated by register/fill
 */
public class EventGenerator {

    private LocationData locationData;
    private int[] years = {1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000};
    private int[] nums = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
    private int[] tens = {40, 50, 60, 70, 80, 90};

    public EventGenerator(){
        File locations = new File("C:/Users/jacob/IdeaProjects/FamilyMap/fms/json/locations.json");

        try (Reader reader = new FileReader(locations)){
            Gson gson = new Gson();

            locationData = gson.fromJson(reader, LocationData.class);

        }
        catch (IOException e) {
            e.printStackTrace();
        }


    }
    public class Location {
        String country;
        String city;
        float latitude;
        float longitude;

        public Location(final String country, final String city, final float latitude, final float longitude) {
            this.country = country;
            this.city = city;
            this.latitude = latitude;
            this.longitude = longitude;
        }

        public String getCountry() {
            return this.country;
        }

        public String getCity() {
            return this.city;
        }

        public float getLatitude() {
            return this.latitude;
        }

        public float getLongitude() {
            return this.longitude;
        }
    }

    class LocationData {
        Location[] data;
    }

    public Location getLocation(){
        return getRandom(locationData.data);
    }
    private Location getRandom(Location[] array) {
        int ran = new Random().nextInt(array.length);
        return array[ran];
    }
    private int getRandomYear(int[] array) {
        int ran = new Random().nextInt(array.length);
        return array[ran];
    }
    public int getBirthYear(int generations) {
        int ran = new Random().nextInt(years.length);
        return (years[ran] - (25 * generations));
    }
    public int getDeathYear(int birthYear){
        int ran = new Random().nextInt(nums.length);
        int ranTen = new Random().nextInt(tens.length);
        return (birthYear + tens[ranTen] + nums[ran]);
    }
    public int getMarriageYear(int birthYear) {
        int ran = new Random().nextInt(nums.length);
        return (birthYear + 18 + nums[ran]);
    }
}
