package service;

import com.google.gson.Gson;

import java.io.*;
import java.util.ArrayList;
import java.util.Random;

/**
 * This object generates names for persons generated by the server
 */
public class NameGenerator {

    BoyNames boyNames;
    GirlNames girlNames;
    LastNames lastNames;

    public NameGenerator(){
        File mnames = new File("C:/Users/jacob/IdeaProjects/FamilyMap/fms/json/mnames.json");
        File fnames = new File("C:/Users/jacob/IdeaProjects/FamilyMap/fms/json/fnames.json");
        File snames = new File("C:/Users/jacob/IdeaProjects/FamilyMap/fms/json/snames.json");
        try (Reader reader = new FileReader(mnames)){
            Gson gson = new Gson();

            boyNames = gson.fromJson(reader, BoyNames.class);

        }
        catch (IOException e) {
            e.printStackTrace();
        }
        try (Reader reader = new FileReader(fnames)){
            Gson gson = new Gson();

            girlNames = gson.fromJson(reader, GirlNames.class);

        }
        catch (IOException e) {
            e.printStackTrace();
        }
        try (Reader reader = new FileReader(snames)){
            Gson gson = new Gson();

            lastNames = gson.fromJson(reader, LastNames.class);

        }
        catch (IOException e) {
            e.printStackTrace();
        }

    }
    public String getBoyName(){
        return getRandom(boyNames.data);
    }
    public String getGirlName(){
        return getRandom(girlNames.data);
    }
    public String getLastName(){
        return getRandom(lastNames.data);
    }
    private String getRandom(String[] array) {
        int ran = new Random().nextInt(array.length);
        return array[ran];
    }
    class BoyNames{
        String[] data;
    }
    class GirlNames{
        String[] data;
    }
    class LastNames{
        String[] data;
    }
}
